name: ci-cd-pipleline to docker hub 
on: 
  push: 
    branches:
    - 'master'
jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Repository Checkout
          uses: actions/checkout@v2 
         
        - name: Login to you Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         
        - name: Setup Docker BuildX
          uses: docker/setup-buildx-action@v1
          
        -  name: Build and Push images to Docker Host
           uses: docker/build-push-action@v2
           with:      
            context: .
            file: ./WebApp/Dockerfile, ./WebAPI/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerwebapp , ${{ secrets.DOCKER_HUB_USERNAME }}/dockerwebapi:latest
             
            
           
          
           
  
