name: ci-cd-pipleline to docker hub 

on: 
  push: 
    branches:
    - 'master'
jobs:
    build:
      runs-on: ubuntu-latest
      strategy: 
        matrix: 
          include:
            - dockerfile: ./WebApp/Dockerfile
              image: ${{ secrets.DOCKER_HUB_USERNAME }}/dockertutorialWebApp:latest
            - dockerfile: ./WebAPI/Dockerfile
              image: ${{ secrets.DOCKER_HUB_USERNAME }}/dockertutorialWebApi:latest
      
      steps:
        - name: Repository Checkout
          uses: actions/checkout@v2       
               
        - name: Login to you Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         
        - name: Setup Docker BuildX
          uses: docker/setup-buildx-action@v1
          
        -  name: Build and Push
           uses: docker/build-push-action@v2
           with: 
            file: ${{ matrix.dockerfile }}            
            push: true
            tags: ${{ matrix.image }}
             
            
           
          
           
  
